### ISSUE TITLE
Calculation of time usage round medians and 75 percentiles

### ISSUE THREAD

**Issue by Mankro** [Aalto-LeTech/mooc-jutut#12]
The time usage app computes medians and 75th percentiles from the students' time usage (based on their own estimates in the chapter feedback questionnaires). 

The median of the sum of the week's (exercise round) time usage is computed by adding together medians from each exercise in the week. I first assumed that the weekly median would be the median from each student's personal weekly sum. That is, if you first count each student's weekly sum and take the median from those sums, you get a different number than in the current implementation which adds up exercise medians for all exercises in the week. Which kind of weekly median is really more useful?

The 75th percentile has the same problem.

https://github.com/Aalto-LeTech/mooc-jutut/blob/911ac911c3b8c8e93d9f1ce511f38a1a7c61015b/timeusage/views.py#L37-L38

**Comment by jsorva** [comment]
For my course planning at least, the sum of the component-specific medians is definitely more useful than the median of the student-specific sums. (It provides a basis for estimating the expect workload for someone who does each component.)

**Comment by Mankro** [comment]
In that case, the current implementation is better.
